name: Docker Image CI

on:
  push:
    branches:
    - master

jobs:
  build: 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    
    - name: Login to docker registry
      uses: actions/docker/login@master
      env:
        DOCKER_REGISTRY_URL: https://hub.docker.com
    
    - name: Build the Docker image
      run: docker build . --tag xobed/kinodnes
